backend:
  name: git-gateway
  branch: master
media_folder: "_stie/images/uploads"
public_forlder: "/images/uploads"

collections: 
  - name: "posts"
    label: "Posts"
    folder: "posts"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "layout/post.njk"}
      - { label: "Title", name: "title", widget: "string"}
      - { label:"Description", name: "decription"}, widget: "string"}
      - { label: "Date", name: "date", widget:"date", default: ""}
      - { label: "Post Body", name: "body", widget: "markdown"}
      - { label:"Featured Image", name:"featuredImage", widget: "image"}
